apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: live-streaming
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ${DOCKER_REGISTRY}/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: jwt-secret
            - name: OME_API_URL
              value: "http://ome:8081"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: mongodb-uri
                  optional: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: live-streaming
spec:
  selector:
    app: backend
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vod-uploader
  namespace: live-streaming
  labels:
    app: vod-uploader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vod-uploader
  template:
    metadata:
      labels:
        app: vod-uploader
    spec:
      containers:
        - name: vod-uploader
          image: ${DOCKER_REGISTRY}/backend:latest
          command: ["node", "src/services/vodUploader.js"]
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: "production"
            - name: OME_RECORDS_PATH
              value: "/opt/ovenmediaengine/records"
            - name: BACKEND_API
              value: "http://backend:3000"
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: api-token
            - name: STORAGE_BUCKET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: storage-bucket
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/app/gcs-credentials.json"
          volumeMounts:
            - name: ome-records
              mountPath: /opt/ovenmediaengine/records
              readOnly: true
            - name: gcs-credentials
              mountPath: /app/gcs-credentials.json
              subPath: gcs-credentials.json
              readOnly: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: ome-records
          persistentVolumeClaim:
            claimName: ome-records-pvc
        - name: gcs-credentials
          secret:
            secretName: gcs-credentials
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: live-streaming
type: Opaque
data:
  jwt-secret: eW91cl9qd3Rfc2VjcmV0X2tleV9jaGFuZ2VfdGhpc19pbl9wcm9kdWN0aW9u # your_jwt_secret_key_change_this_in_production
  api-token: # To be generated
  storage-bucket: # Your GCS bucket name
  mongodb-uri: # Optional MongoDB URI
